:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY") { 10 }.to_i %>
:queues:
  - high
  - default
  - low
:scheduler:
  :schedule:
    fetch_new_events_job:
      cron: "*/5 * * * *" # Every 5 minutes
      class: "FetchNewEventsJob"
      queue: high
      enabled: false
    clean_up_events_job:
      cron: "*/5 * * * *" # Every 5 minutes
      class: "CleanUpEventsJob"
      queue: low
      enabled: false
    clean_up_playlists_job:
      cron: "0 * * * *" # Every hour
      class: "CleanUpPlaylistsJob"
      queue: low
      enabled: false
